# Build customization
builds:
  -
    main: ./cmd/dcsub2srt/main.go
    binary: dcsub2srt
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  -
    main: ./cmd/ssa2srt/main.go
    binary: ssa2srt
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
  -
    main: ./cmd/subber/main.go
    binary: subber
    goos:
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
# Archive customization
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
  files:
    - README.md
    - LICENSE
